// <auto-generated />
namespace UniversityOfRoommates.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class modifycasa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modifycasa));
        
        string IMigrationMetadata.Id
        {
            get { return "201706101636505_modify casa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
