// <auto-generated />
namespace UniversityOfRoommates.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TESTuseaccountaspnetasour : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TESTuseaccountaspnetasour));
        
        string IMigrationMetadata.Id
        {
            get { return "201706091625561_TEST use account asp.net as our"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
